--Ethan Backhaus

Create TABLE STUDIO(
STUDIOID CHAR(3) NOT NULL,
STUDIONAME VARCHAR2(25) NOT NULL,
CONSTRAINT STUDIO_PK PRIMARY KEY(STUDIOID));

CREATE TABLE ANIME (
ANIMEID CHAR(4) NOT NULL,
ANIMENAME VARCHAR2(50) NOT NULL,
ABBREVIATION VARCHAR2(4),
EPISODETOTAL NUMBER(2,0) NOT NULL,
SOURCEMATERIAL VARCHAR2(15) NOT NULL,
AIRDATE DATE NOT NULL,
OVERALLRATING NUMBER(3,2) NULL,
FOLLOWINGMEMBERS NUMBER NULL,
STUDIOID CHAR(3) NOT NULL,
CONSTRAINT ANIME_PK PRIMARY KEY (ANIMEID),
CONSTRAINT ANIME_FK FOREIGN KEY (STUDIOID) REFERENCES STUDIO(STUDIOID));

CREATE TABLE GENRE(
ANIMEID CHAR(4) NOT NULL,
GENRE VARCHAR2(25) NOT NULL,
CONSTRAINT GENRE_PK PRIMARY KEY(ANIMEID,GENRE),
CONSTRAINT GENRE_FK FOREIGN KEY (ANIMEID) REFERENCES ANIME(ANIMEID));


Drop Table Anime;
Drop table Genre;



